docker:
  image: g4s8/rultor-jdk11:alpine3.10
architect:
  - amihaiemil
assets:
  settings.xml: "amihaiemil/maven#settings.xml"
  pubring.gpg: "amihaiemil/maven#pubring.gpg"
  secring.gpg: "amihaiemil/maven#secring.gpg"
env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk
merge:
  script: |-
    mvn clean install --settings /home/r/settings.xml
deploy:
  script: |-
    echo 'Nothing to deploy'
    exit -1
release:
  script: |-
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    chmod +x ./rrv.sh
    ./rrv.sh
